name: Update Metadata
on:
  release:
    types: [published]

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1️⃣ Install jq
      - run: sudo apt-get install -y jq

      # 2️⃣ Parse release data
      - name: Extract release data
        id: extract
        run: |
          NAME="${GITHUB_REPOSITORY##*/}"
          VERSION="${GITHUB_REF_NAME}"

          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 3️⃣ Update the metadata.json
      - name: Update metadata.json
        run: |
          FILE=metadata.json

          if [ ! -f $FILE ]; then
            echo "[]" > $FILE
          fi

          cat $FILE | jq \
            --arg name "${{ steps.extract.outputs.name }}" \
            --arg version "${{ steps.extract.outputs.version }}" \
            '(.[] | select(.name == $name) | .latest_version) |= $version
              | if (.[] | select(.name == $name)) then . else . + [{"name": $name, "latest_version": $version }] end' \
            > temp.json && mv temp.json $FILE

      # 4️⃣ Commit and Push
      - name: Push updated metadata.json
        uses: EndBug/add-and-commit@v9
        with:
          add: "metadata.json"
          message: "Update metadata.json for ${{ steps.extract.outputs.name }}@${{ steps.extract.outputs.version }}"
